parameters:
  - name: environment
    type: string
    default: Dev
  - name: location
    type: string
    default: 'uksouth'
  - name: azureSubscription
    type: string
    default: 'AppServicesDevOps-NonProd'
  - name: method
    type: string
    default: 'GET'
  - name: retries
    type: number
    default: 5
  - name: secondsDelay
    type: number
    default: 10
  - name: timeoutSec
    type: number
    default: 120
  - name: merchantCode
    type: string
  - name: paymentReceiptServiceUrl
    type: string
  - name: worldpayPassword
    type: string
  - name: worldpayPaymentServiceUrl
    type: string
  - name: worldpayUsername
    type: string

jobs:
  - deployment:
    displayName: Deploying Web Apps - WorldpayProxy
    environment: ${{ parameters.environment }}
    strategy:
       runOnce:
         deploy:
          steps:
            - task: AzureRmWebAppDeployment@4
              displayName: 'Azure Web App Deploy'
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: ${{ parameters.azureSubscription }}
                appType: 'webApp'
                WebAppName: 'app-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-worldpay-api'
                deployToSlotOrASE: true
                ResourceGroupName: 'rg-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-common'
                SlotName: 'staging'
                packageForLinux: '$(Pipeline.Workspace)/**/Insolvency.CommonServices.WorldpayProxy.zip'
                RemoveAdditionalFilesFlag: true

            - task: AzureAppServiceSettings@1
              displayName: Apply App Service Settings
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                appName: 'app-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-worldpay-api'
                slotName: 'staging'
                appSettings: |
                  [
                    {
                      "name": "Environ",
                      "value": "${{ lower(parameters.environment) }}",
                      "slotSetting": false
                    },
                    {
                      "name": "MerchantCode",
                      "value": "${{ parameters.merchantCode }}",
                      "slotSetting": false
                    },
                    {
                      "name": "PaymentReceiptServiceUrl",
                      "value": "${{ parameters.paymentReceiptServiceUrl }}",
                      "slotSetting": false
                    },
                    {
                      "name": "WorldpayPassword",
                      "value": "${{ parameters.worldpayPassword }}",
                      "slotSetting": false
                    },
                    {
                      "name": "WorldpayPaymentServiceUrl",
                      "value": "${{ parameters.worldpayPaymentServiceUrl }}",
                      "slotSetting": false
                    },
                    {
                      "name": "WorldpayUsername",
                      "value": "${{ parameters.worldpayUsername }}",
                      "slotSetting": false
                    }
                  ]
      
            - task: AzureAppServiceManage@0
              displayName: Start Staging Slot
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                Action: 'Start Azure App Service'
                WebAppName: 'app-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-worldpay-api'
                ResourceGroupName: 'rg-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-common'              
                SpecifySlotOrASE: true
                Slot: 'staging'

            - checkout: inss-devops-common-lib

            - task: PowerShell@2
              displayName: 'Performing Health Check - Staging'    
              inputs:
                failOnStderr: true
                targetType: 'filePath'
                filePath: $(System.DefaultWorkingDirectory)\powershell\InvokeRequestWithRetry.ps1
                arguments: > # Use this to avoid newline characters in multi-line string
                  -URI "https://app-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-worldpay-api-staging.azurewebsites.net"
                  -Method "${{ parameters.method }}"
                  -Retries ${{ parameters.retries }}
                  -SecondsDelay ${{ parameters.secondsDelay }}
                  -TimeoutSec ${{ parameters.timeoutSec }} 
            
            - task: AzureAppServiceManage@0
              displayName: Swap Staging Slot into Production
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                Action: 'Swap Slots'
                WebAppName: 'app-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-worldpay-api'
                ResourceGroupName: 'rg-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-common'
                SourceSlot: 'staging'
                SwapWithProduction: true

            - task: PowerShell@2
              displayName: 'Performing Health Check - Production'    
              inputs:
                failOnStderr: true
                targetType: 'filePath'
                filePath: $(System.DefaultWorkingDirectory)\powershell\InvokeRequestWithRetry.ps1
                arguments: > # Use this to avoid newline characters in multi-line string
                  -URI "https://app-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-worldpay-api.azurewebsites.net"
                  -Method "${{ parameters.method }}"
                  -Retries ${{ parameters.retries }}
                  -SecondsDelay ${{ parameters.secondsDelay }}
                  -TimeoutSec ${{ parameters.timeoutSec }} 

            - task: AzureAppServiceManage@0
              displayName: Stop Staging Slot
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                Action: 'Stop Azure App Service'
                WebAppName: 'app-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-worldpay-api'
                ResourceGroupName: 'rg-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-common'              
                SpecifySlotOrASE: true
                Slot: 'staging'  


  - deployment:
    displayName: Deploying Web Apps - MockWorldpay
    environment: ${{ parameters.environment }}
    strategy:
       runOnce:
         deploy:
          steps:
            - task: AzureRmWebAppDeployment@4
              displayName: 'Azure Web App Deploy'
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: ${{ parameters.azureSubscription }}
                appType: 'webApp'
                WebAppName: 'app-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-mock-worldpay-api'
                deployToSlotOrASE: true
                ResourceGroupName: 'rg-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-common'
                SlotName: 'staging'
                packageForLinux: '$(Pipeline.Workspace)/**/Insolvency.CommonServices.MockWorldpay.zip'
                RemoveAdditionalFilesFlag: true

            - task: AzureAppServiceSettings@1
              displayName: Apply App Service Settings
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                appName: 'app-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-mock-worldpay-api'
                slotName: 'staging'
                appSettings: |
                  [
                    {
                      "name": "Environ",
                      "value": "${{ lower(parameters.environment) }}",
                      "slotSetting": false
                    }
                  ]
      
            - task: AzureAppServiceManage@0
              displayName: Start Staging Slot
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                Action: 'Start Azure App Service'
                WebAppName: 'app-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-mock-worldpay-api'
                ResourceGroupName: 'rg-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-common'              
                SpecifySlotOrASE: true
                Slot: 'staging'

            - checkout: inss-devops-common-lib

            - task: PowerShell@2
              displayName: 'Performing Health Check - Staging'    
              inputs:
                failOnStderr: true
                targetType: 'filePath'
                filePath: $(System.DefaultWorkingDirectory)\powershell\InvokeRequestWithRetry.ps1
                arguments: > # Use this to avoid newline characters in multi-line string
                  -URI "https://app-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-mock-worldpay-api-staging.azurewebsites.net"
                  -Method "${{ parameters.method }}"
                  -Retries ${{ parameters.retries }}
                  -SecondsDelay ${{ parameters.secondsDelay }}
                  -TimeoutSec ${{ parameters.timeoutSec }} 
            
            - task: AzureAppServiceManage@0
              displayName: Swap Staging Slot into Production
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                Action: 'Swap Slots'
                WebAppName: 'app-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-mock-worldpay-api'
                ResourceGroupName: 'rg-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-common'
                SourceSlot: 'staging'
                SwapWithProduction: true

            - task: PowerShell@2
              displayName: 'Performing Health Check - Production'    
              inputs:
                failOnStderr: true
                targetType: 'filePath'
                filePath: $(System.DefaultWorkingDirectory)\powershell\InvokeRequestWithRetry.ps1
                arguments: > # Use this to avoid newline characters in multi-line string
                  -URI "https://app-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-mock-worldpay-api.azurewebsites.net"
                  -Method "${{ parameters.method }}"
                  -Retries ${{ parameters.retries }}
                  -SecondsDelay ${{ parameters.secondsDelay }}
                  -TimeoutSec ${{ parameters.timeoutSec }} 

            - task: AzureAppServiceManage@0
              displayName: Stop Staging Slot
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                Action: 'Stop Azure App Service'
                WebAppName: 'app-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-mock-worldpay-api'
                ResourceGroupName: 'rg-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-common'              
                SpecifySlotOrASE: true
                Slot: 'staging'  