parameters:
  - name: environment
    type: string
    default: Dev
  - name: location
    type: string
    default: 'uksouth'
  - name: azureSubscription
    type: string
    default: 'AppServicesDevOps-NonProd'
  - name: method
    type: string
    default: 'GET'
  - name: retries
    type: number
    default: 5
  - name: secondsDelay
    type: number
    default: 10
  - name: timeoutSec
    type: number
    default: 120
  - name: merchantCode
    type: string
  - name: appInsightsConnectionString
    type: string
  - name: worldpayPaymentServiceUrl
    type: string
  
jobs:
  - deployment:
    displayName: Deploying Function Apps - WorldpayProxy
    environment: ${{ parameters.environment }}
    strategy:
       runOnce:
         deploy:
          steps:
            - task: AzureFunctionApp@1
              displayName: 'Azure Function App Deploy'
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: ${{ parameters.azureSubscription }}
                appType: 'functionApp'
                appName: 'func-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-worldpay-api'
                deployToSlotOrASE: true
                ResourceGroupName: 'rg-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-common'
                SlotName: 'staging'
                package: '$(Pipeline.Workspace)/**/*.zip'
                RemoveAdditionalFilesFlag: true

            - task: AzureAppServiceSettings@1
              displayName: Apply App Service Settings
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                appName: 'func-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-worldpay-api'
                slotName: 'staging'
                appSettings: |
                  [
                    {
                      "name": "Environ",
                      "value": "${{ lower(parameters.environment) }}",
                      "slotSetting": false
                    },
                    {
                      "name": "SiteSitting__MerchantCode",
                      "value": "${{ parameters.merchantCode }}",
                      "slotSetting": false
                    },
                    {
                      "name": "ExternalAppSettings__WorldPayWebAppBaseUrl",
                      "value": "https://app-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-bankruptcy-api.azurewebsites.net/v1/",
                      "slotSetting": false
                    },
                    {
                      "name": "ExternalAppSettings__PaymentReceiptServiceUrl:",
                      "value": "https://app-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-bankruptcy-api.azurewebsites.net/v1/",
                      "slotSetting": false
                    },
                    {
                      "name": "ExternalAppSettings__WorldpayPaymentServiceUrl",
                      "value": "${{ parameters.worldpayPaymentServiceUrl }}",
                      "slotSetting": false
                    },
                    {
                      "name": "ExternalAppSettings__WorldPayDtdUrl",
                      "value": "https://app-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-bankruptcy-api.azurewebsites.net/v1/",
                      "slotSetting": false
                    },
                    {
                      "name": "CredentialsSettings__WorldpayPassword",
                      "value": "@Microsoft.KeyVault(VaultName=kv-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods;SecretName=worldpay-password)",
                      "slotSetting": false
                    },
                    {
                      "name": "CredentialsSettings__WorldpayUsername",
                      "value": "@Microsoft.KeyVault(VaultName=kv-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods;SecretName=worldpay-username)",
                      "slotSetting": false
                    },
                    {
                      "name": "APPLICATIONINSIGHTS_CONNECTION_STRING",
                      "value": "${{ parameters.appInsightsConnectionString }}",
                      "slotSetting": false
                    }
                  ]
      
            - task: AzureAppServiceManage@0
              displayName: Start Staging Slot
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                Action: 'Start Azure App Service'
                WebAppName: 'func-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-worldpay-api'
                ResourceGroupName: 'rg-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-common'              
                SpecifySlotOrASE: true
                Slot: 'staging'

            - checkout: inss-devops-common-lib

            - task: PowerShell@2
              displayName: 'Performing Health Check - Staging'    
              inputs:
                failOnStderr: true
                targetType: 'filePath'
                filePath: $(System.DefaultWorkingDirectory)\powershell\InvokeRequestWithRetry.ps1
                arguments: > # Use this to avoid newline characters in multi-line string
                  -URI "https://func-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-worldpay-api-staging.azurewebsites.net/api/health/ping?"
                  -Method "${{ parameters.method }}"
                  -Retries ${{ parameters.retries }}
                  -SecondsDelay ${{ parameters.secondsDelay }}
                  -TimeoutSec ${{ parameters.timeoutSec }} 
            
            - task: AzureAppServiceManage@0
              displayName: Swap Staging Slot into Production
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                Action: 'Swap Slots'
                WebAppName: 'func-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-worldpay-api'
                ResourceGroupName: 'rg-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-common'
                SourceSlot: 'staging'
                SwapWithProduction: true

            - task: PowerShell@2
              displayName: 'Performing Health Check - Production'    
              inputs:
                failOnStderr: true
                targetType: 'filePath'
                filePath: $(System.DefaultWorkingDirectory)\powershell\InvokeRequestWithRetry.ps1
                arguments: > # Use this to avoid newline characters in multi-line string
                  -URI "https://func-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-worldpay-api.azurewebsites.net/api/health/ping?"
                  -Method "${{ parameters.method }}"
                  -Retries ${{ parameters.retries }}
                  -SecondsDelay ${{ parameters.secondsDelay }}
                  -TimeoutSec ${{ parameters.timeoutSec }} 

            - task: AzureAppServiceManage@0
              displayName: Stop Staging Slot
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                Action: 'Stop Azure App Service'
                WebAppName: 'func-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-worldpay-api'
                ResourceGroupName: 'rg-${{ parameters.location }}-${{ lower(parameters.environment) }}-ods-common'              
                SpecifySlotOrASE: true
                Slot: 'staging'  
